//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LennujaamRogovski
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lennujaam_RogovskiContainer : DbContext
    {
        public lennujaam_RogovskiContainer()
            : base("name=lennujaam_RogovskiContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<lend> lendSet { get; set; }
        public virtual DbSet<lennuk> lennukSet { get; set; }
    }
}
